name: appcolegio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.5.0'  # Restricción mínima recomendada

dependencies:
  flutter:
    sdk: flutter
  
  # Para realizar peticiones HTTP
  http: ^1.3.0
  
  # Íconos de iOS
  cupertino_icons: ^1.0.8

  # Para abrir enlaces externos (por ejemplo, PDFs en el navegador)
  url_launcher: ^6.2.4

  # Para manejo de fechas, formateo, internacionalización, etc.
  intl: 0.19.0

  # Para localizaciones en Flutter
  flutter_localizations:
    sdk: flutter

  # Para seleccionar archivos (si lo necesitas en otra parte de tu proyecto)
  file_picker: ^8.0.2

  # Para obtener rutas en el sistema de archivos (si lo necesitas)
  path_provider: any

  # Visor de PDF dentro de la app (puedes quitarlo si no lo usas)
  syncfusion_flutter_pdfviewer: ^24.1.45

  # Agrega la dependencia flutter_svg aquí
  flutter_svg: ^2.0.10  # Puedes verificar la última versión disponible en pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/comida_perros1.png
    - assets/images/comida_perros2.png
    - assets/images/comida_perros3.png
    - assets/images/comida_perros4.png
    - assets/images/comida_perros5.png
    - assets/images/comida_perros6.png
    - assets/images/comida_cerdos1.png
    - assets/images/comida_cerdos2.png
    - assets/images/comida_cerdos3.png
    - assets/images/comida_cerdos4.png
    - assets/images/comida_cerdos5.png
    - assets/images/comida_gallinas1.png
    - assets/images/comida_gallinas2.png
    - assets/images/comida_gallinas3.png
    - assets/images/comida_gallinas4.png
    - assets/images/comida_gallinas5.png
    - assets/images/comida_gallinas6.png
    - assets/images/portada.png
